[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-learn-py"
version = "0.1.0"
description = "A comprehensive MCP (Model Context Protocol) server implementation for learning purposes (Python 3.9 compatible)"
authors = [
    { name = "MCP Learner", email = "learner@example.com" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

dependencies = [
    # Use alternative libraries compatible with Python 3.9
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "structlog>=23.2.0",
    "httpx>=0.25.0",
    "beautifulsoup4>=4.12.0",
    "python-dotenv>=1.0.0",
    "psutil>=5.9.0",
    "aiofiles>=23.2.1",
    # JSON-RPC implementation instead of MCP library
    "jsonrpc-base>=2.1.0",
    "jsonrpc-async>=2.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "black>=23.9.0",
    "isort>=5.12.0",
    "flake8>=6.1.0",
    "mypy>=1.6.0",
    "pre-commit>=3.5.0",
]